/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import Class.Slide;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaime
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Algebra Lineal");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHome = new javax.swing.JPanel();
        LTitleHome = new javax.swing.JLabel();
        BExit = new javax.swing.JButton();
        BMiniaze = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PControl = new javax.swing.JPanel();
        BOperations = new javax.swing.JLabel();
        BType = new javax.swing.JLabel();
        BTxt1 = new javax.swing.JLabel();
        BTxt22 = new javax.swing.JLabel();
        BTxt3 = new javax.swing.JLabel();
        BHome = new javax.swing.JLabel();
        LType = new javax.swing.JLabel();
        LTxt1 = new javax.swing.JLabel();
        LIOptions = new javax.swing.JLabel();
        LTxt2 = new javax.swing.JLabel();
        LTxt3 = new javax.swing.JLabel();
        LOperaciones = new javax.swing.JLabel();
        LHome = new javax.swing.JLabel();
        LIHome = new javax.swing.JLabel();
        LIHome1 = new javax.swing.JLabel();
        LIHome2 = new javax.swing.JLabel();
        LIHome3 = new javax.swing.JLabel();
        LIHome4 = new javax.swing.JLabel();
        LPanel = new javax.swing.JLabel();
        PAddMatrix = new javax.swing.JPanel();
        LManageMx = new javax.swing.JLabel();
        PBackground = new javax.swing.JPanel();
        LBackground = new javax.swing.JLabel();

        PHome.setOpaque(false);
        PHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTitleHome.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        LTitleHome.setForeground(new java.awt.Color(255, 255, 255));
        LTitleHome.setText("HOME");
        PHome.add(LTitleHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px.png"))); // NOI18N
        BExit.setBorder(null);
        BExit.setBorderPainted(false);
        BExit.setContentAreaFilled(false);
        BExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BExitMouseClicked(evt);
            }
        });
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        getContentPane().add(BExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 8, -1, -1));

        BMiniaze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        BMiniaze.setBorder(null);
        BMiniaze.setBorderPainted(false);
        BMiniaze.setContentAreaFilled(false);
        BMiniaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMiniazeActionPerformed(evt);
            }
        });
        getContentPane().add(BMiniaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 8, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton_on.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton_on.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 190, 50, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_off.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 150, 50, 50));

        PControl.setAlignmentX(0.0F);
        PControl.setAlignmentY(0.0F);
        PControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PControl.add(BOperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 60));
        PControl.add(BType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));
        PControl.add(BTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 50));
        PControl.add(BTxt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 60));
        PControl.add(BTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 60));

        BHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHomeMouseClicked(evt);
            }
        });
        PControl.add(BHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 50));

        LType.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LType.setForeground(new java.awt.Color(255, 59, 10));
        LType.setText("Type");
        PControl.add(LType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        LTxt1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LTxt1.setForeground(new java.awt.Color(255, 59, 10));
        LTxt1.setText("Txt1");
        PControl.add(LTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        LIOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_32px.png"))); // NOI18N
        LIOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LIOptionsMouseClicked(evt);
            }
        });
        PControl.add(LIOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 30));

        LTxt2.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LTxt2.setForeground(new java.awt.Color(255, 59, 10));
        LTxt2.setText("Txt2");
        PControl.add(LTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        LTxt3.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LTxt3.setForeground(new java.awt.Color(255, 59, 10));
        LTxt3.setText("Txt3");
        PControl.add(LTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        LOperaciones.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LOperaciones.setForeground(new java.awt.Color(255, 59, 10));
        LOperaciones.setText("Operations");
        PControl.add(LOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        LHome.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        LHome.setForeground(new java.awt.Color(255, 59, 10));
        LHome.setText("Home");
        PControl.add(LHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        LIHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Bar_Chart_32px.png"))); // NOI18N
        PControl.add(LIHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        LIHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Monitor_32px.png"))); // NOI18N
        PControl.add(LIHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        LIHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Mouse_32px.png"))); // NOI18N
        PControl.add(LIHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        LIHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        PControl.add(LIHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        LIHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        PControl.add(LIHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        LPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PANEL.png"))); // NOI18N
        PControl.add(LPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 230, 497));

        getContentPane().add(PControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 2, 230, 497));

        PAddMatrix.setOpaque(false);
        PAddMatrix.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LManageMx.setFont(new java.awt.Font("Consolas", 3, 36)); // NOI18N
        LManageMx.setForeground(new java.awt.Color(255, 255, 255));
        LManageMx.setText("MANAGE MATRIX");
        PAddMatrix.add(LManageMx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(PAddMatrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        PBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.png"))); // NOI18N
        PBackground.add(LBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(PBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LIOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIOptionsMouseClicked
        // TODO add your handling code here:
        Slide.jPanelXDerecha(-180, 0, 10, 5, PControl);
        Slide.jPanelXIzquierda(0, -180, 10, 5, PControl);
    }//GEN-LAST:event_LIOptionsMouseClicked

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
        int validacion = JOptionPane.showConfirmDialog(null, "Desea cerrar el sistema?", "EXIT", JOptionPane.YES_NO_OPTION);
        if(validacion == 0) System.exit(0);
    }//GEN-LAST:event_BExitActionPerformed

    private void BMiniazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMiniazeActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.Login.ICONIFIED);
    }//GEN-LAST:event_BMiniazeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        PHome.setVisible(true);
        PControl.setVisible(true);
        PBackground.setVisible(true);
        PAddMatrix.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PHome.setVisible(false);
        PAddMatrix.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHomeMouseClicked
        // TODO add your handling code here:
        PHome.setVisible(true);
        PAddMatrix.setVisible(false);
    }//GEN-LAST:event_BHomeMouseClicked

    private void BExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExit;
    private javax.swing.JLabel BHome;
    private javax.swing.JButton BMiniaze;
    private javax.swing.JLabel BOperations;
    private javax.swing.JLabel BTxt1;
    private javax.swing.JLabel BTxt22;
    private javax.swing.JLabel BTxt3;
    private javax.swing.JLabel BType;
    private javax.swing.JLabel LBackground;
    private javax.swing.JLabel LHome;
    private javax.swing.JLabel LIHome;
    private javax.swing.JLabel LIHome1;
    private javax.swing.JLabel LIHome2;
    private javax.swing.JLabel LIHome3;
    private javax.swing.JLabel LIHome4;
    private javax.swing.JLabel LIOptions;
    private javax.swing.JLabel LManageMx;
    private javax.swing.JLabel LOperaciones;
    private javax.swing.JLabel LPanel;
    private javax.swing.JLabel LTitleHome;
    private javax.swing.JLabel LTxt1;
    private javax.swing.JLabel LTxt2;
    private javax.swing.JLabel LTxt3;
    private javax.swing.JLabel LType;
    private javax.swing.JPanel PAddMatrix;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PControl;
    private javax.swing.JPanel PHome;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
